# Generated by Django 6.0.5 on 2026-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_goal_category_remove_goal_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
